# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: dbyll
google_analytics: 
title: JY

collections: 
  elasticsearch:
    output: true
    permalink: /elasticsearch/:name
  share:
    output: true
    permalink: /share/:name
  os:
    output: true
    permalink: /os/:name

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: "JY"

description: "JY的笔记本"
author:
  name: JY
  email: jingyu525@gmail.com
  github: liujingyu
  bio: 
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
about_path: about

# set it as url of an image
sidebar_background_image: /assets/media/sky.png

BASE_PATH:

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
